[core]
data_directory = /var/lib/openwebrx
temporary_directory = /tmp
log_level = INFO

[web]
port = 8073
ipv6 = true
ssl_certificate = /etc/openwebrx/cert.pem
ssl_key = /etc/openwebrx/key.pem

[aprs]
symbols_path = /usr/share/aprs-symbols/png
